on:
  workflow_run:
    workflows: ["Daffodil Build"]
    types:
      - completed

#####
# WARNING: This code operates in a privileged context.
#####
# We only allow workflow runs from forks that we know are safe via a control
# in the Github UI called "Require approval for all outside collaborators".
#    
# It's a little painful to have to keep clicking the button in the UI,
# but it's generally safer for us (from a security standpoint), 
# while still allowing trusted users to contribute 
# to the project without annoying CI failures.
# 
# We have understood the risk and attempted to handle the concern outlined here:
# https://securitylab.github.com/research/github-actions-preventing-pwn-requests/ 
jobs:
  deploy_daffio:
    name: Deploy Daff.io
    runs-on: ubuntu-latest 
    environment: 
      name: preview
      url: ${{ steps.vercel-deploy.outputs.url }}
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    steps:
      - name: 'Download artifact'
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{ github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "daffio-16.x"
            })[0];
            var download = await github.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: matchArtifact.id,
              archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/daffio-16.x.zip', Buffer.from(download.data))
      
      - run: ls -Al .
        name: Review Folder    
           
      - run: unzip -q daffio-16.x -d . && rm daffio-16.x
        name: Unzip internal artifact zip

      - run: ls -Al .
        name: Review Folder    

      - run: unzip -q daffio.zip -d . && rm daffio.zip
        name: Unzip internal artifact zip

      - uses: graycoreio/github-actions/angular-universal-vercel@main
        id: vercel-deploy
        with:
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_org: ${{ secrets.VERCEL_ORG }}
          vercel_project_id: ${{ secrets.VERCEL_NEXT_PROJECT_ID }}
